name: navigator
channels:
  - defaults
  - conda-forge
dependencies:
  - asn1crypto=0.24.0=py36_1003
  - basemap=1.2.0=py36hf62cb97_3
  - blas=1.1=openblas
  - boost-cpp=1.68.0=h11c811c_1000
  - bzip2=1.0.6=h14c3975_1002
  - ca-certificates=2019.3.9=hecc5488_0
  - cachetools=2.0.1=py_0
  - cairo=1.16.0=ha4e643d_1000
  - cartopy=0.17.0=py36h0aa2c8f_1004
  - certifi=2019.3.9=py36_0
  - cffi=1.11.5=py36_0
  - cftime=1.0.0=py36_0
  - chardet=3.0.4=py36_1003
  - click=7.0=py_0
  - cloudpickle=1.2.0=py_0
  - cmocean=2.0=py_0
  - configobj=5.0.6=py_0
  - cryptography=2.7=py36h72c5cf5_0
  - cycler=0.10.0=py_1
  - cytoolz=0.9.0.1=py36h14c3975_1001
  - dask=1.2.2=py_3
  - dbus=1.13.6=he372182_0
  - expat=2.2.5=hf484d3e_1002
  - flask-babel=0.11.2=py_1
  - flask-compress=1.4.0=py_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_0
  - freexl=1.0.5=h14c3975_1002
  - gdal=2.3.3=py36hf242f0b_1
  - geographiclib=1.49=py_0
  - geopy=1.13.0=py_1
  - geos=3.7.1=hf484d3e_1000
  - geotiff=1.4.3=h1105359_1000
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.1.7=h516909a_1
  - glib=2.58.3=hf63aee3_1001
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - gunicorn=19.9.0=py36_1000
  - hdf4=4.2.13=0
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - heapdict=1.0.0=py36_1000
  - icu=58.2=0
  - idna=2.8=py36_1000
  - ipython_genutils=0.2.0=py_1
  - itsdangerous=1.1.0=py_0
  - jansson=2.11=h516909a_1001
  - jinja2=2.10.1=py_0
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h14c3975_1001
  - kealib=1.4.10=h1978553_1003
  - kiwisolver=1.1.0=py36hc9558a2_0
  - krb5=1.16.3=h05b26f9_1001
  - libdap4=3.19.1=hd48c02d_1000
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=3
  - libgdal=2.3.3=hdb8f723_1
  - libiconv=1.15=h516909a_1005
  - libkml=1.3.0=h328b03d_1009
  - libnetcdf=4.6.2=hbdf4f91_1001
  - libpng=1.6.37=hed695b0_0
  - libpq=11.3=h4e4e079_0
  - libspatialite=4.3.0a=hb5ec416_1026
  - libssh2=1.8.2=h22169c7_2
  - libtiff=4.0.10=h57b8799_1003
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_0
  - libxslt=1.1.32=0
  - locket=0.2.0=py_2
  - lxml=4.2.2=py36_0
  - lz4-c=1.8.3=he1b5a44_1001
  - matplotlib=3.1.0=py36_1
  - matplotlib-base=3.1.0=py36hfd891ef_1
  - metpy=0.10.2=py36_0
  - mkl_fft=1.0.13=py36h516909a_1
  - mkl_random=1.0.4=py36hf2d7682_0
  - msgpack-python=0.6.1=py36h6bb024c_0
  - ncurses=6.1=hf484d3e_1002
  - netcdf4=1.5.1.2=py36had58050_0
  - numpy=1.16.2=py36_blas_openblash1522bff_0
  - olefile=0.46=py_0
  - openblas=0.3.3=h9ac9557_1001
  - openjpeg=2.3.1=h58a6597_0
  - openssl=1.1.1b=h14c3975_1
  - packaging=19.0=py_0
  - pandas=0.24.2=py36hb3f55d8_0
  - partd=0.3.10=py_1
  - pcre=8.41=hf484d3e_1003
  - pillow=6.0.0=py36he7afcd5_0
  - pint=0.8.1=py_1
  - pixman=0.34.0=h14c3975_1003
  - ply=3.11=py_1
  - pooch=0.2.1=py36_1000
  - poppler=0.67.0=h2ad7f00_6
  - poppler-data=0.4.9=1
  - postgresql=11.3=hbeee2d4_0
  - proj4=5.2.0=he1b5a44_1003
  - psutil=5.6.2=py36h516909a_0
  - pthread-stubs=0.4=h14c3975_1001
  - pycparser=2.19=py36_1
  - pyepsg=0.4.0=py_0
  - pykdtree=1.3.1=py36h3010b51_1002
  - pyproj=1.9.5.1=py36hc0953d3_1007
  - pyqt=5.9.2=py36hcca6a23_0
  - pyresample=1.9.0=py36_0
  - python-dateutil=2.7.2=py_0
  - pywavelets=1.0.3=py36hd352d35_1
  - pyyaml=5.1.1=py36h516909a_0
  - qt=5.9.7=h52cfd70_2
  - readline=7.0=hf8c457e_1001
  - scikit-image=0.15.0=py36he1b5a44_0
  - scipy=1.1.0=py36_blas_openblash1522bff_1202
  - seawater=3.3.4=py_1
  - shapely=1.6.4=py36h2afed24_1004
  - sip=4.19.8=py36hf484d3e_1000
  - six=1.12.0=py36_1000
  - sortedcontainers=2.1.0=py_0
  - sqlite=3.28.0=h8b20d00_0
  - thredds_crawler=1.5.4=py_1
  - tk=8.6.9=hed695b0_1002
  - toolz=0.9.0=py_1
  - tornado=6.0.2=py36h516909a_0
  - traitlets=4.3.2=py36_1000
  - tzcode=2019a=h516909a_1002
  - urllib3=1.24.3=py36_0
  - uwsgi=2.0.18=py36h4472670_1
  - werkzeug=0.14.1=py_0
  - xerces-c=3.2.2=hac72e42_1001
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.9=h516909a_1004
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.7=h14c3975_1000
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zict=0.1.4=py_0
  - zstd=1.4.0=h3b9ef0a_0
  - babel=2.7.0=py_0
  - basemap-data-hires=1.2.0=0
  - bokeh=1.2.0=py36_0
  - curl=7.62.0=hbc83047_0
  - dask-core=1.2.2=py_0
  - decorator=4.4.0=py_0
  - distributed=1.28.1=py36_0
  - flask=0.12.2=py36_0
  - imageio=2.5.0=py36_0
  - intel-openmp=2019.4=243
  - libcurl=7.62.0=h20c2e04_0
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - markupsafe=1.0=py36_0
  - mkl=2019.4=243
  - networkx=2.3=py_0
  - owslib=0.17.1=py_0
  - pip=19.1.1=py36_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.0=py_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.0=py36_0
  - python=3.6.8=h0371630_0
  - pytz=2019.1=py_0
  - requests=2.22.0=py36_0
  - setuptools=41.0.1=py36_0
  - tblib=1.4.0=py_0
  - wheel=0.33.4=py36_0
  - xarray=0.11.3=py36_0
  - zlib=1.2.11=0
  - pip:
    - msgpack==0.6.1
prefix: /opt/tools/miniconda3/envs/navigator


