name: navigator
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0=py37_1003
  - babel=2.7.0=py_0
  - basemap=1.2.0=py37hf62cb97_3
  - beautifulsoup4=4.7.1=py37_1001
  - boost-cpp=1.68.0=h11c811c_1000
  - bzip2=1.0.6=h14c3975_1002
  - ca-certificates=2019.3.9=hecc5488_0
  - cachetools=3.1.1=py_0
  - cairo=1.16.0=ha4e643d_1000
  - cartopy=0.17.0=py37h0aa2c8f_1004
  - certifi=2019.3.9=py37_0
  - cffi=1.12.3=py37h8022711_0
  - cftime=1.0.3.4=py37hd352d35_1001
  - chardet=3.0.4=py37_1003
  - click=7.0=py_0
  - cloudpickle=1.1.1=py_0
  - cmocean=2.0=py_0
  - configobj=5.0.6=py_0
  - cryptography=2.6.1=py37h72c5cf5_0
  - curl=7.64.1=hf8cf82a_0
  - cycler=0.10.0=py_1
  - cytoolz=0.9.0.1=py37h14c3975_1001
  - dask-core=1.2.2=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.0=py_0
  - expat=2.2.5=hf484d3e_1002
  - flask=1.0.3=py_0
  - flask-babel=0.12.2=py_0
  - flask-compress=1.4.0=py_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_0
  - freexl=1.0.5=h14c3975_1002
  - gdal=2.4.1=py37hf242f0b_0
  - geographiclib=1.49=py_0
  - geopy=1.20.0=py_0
  - geos=3.7.1=hf484d3e_1000
  - geotiff=1.4.3=h1105359_1000
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.1.7=h516909a_1
  - glib=2.58.3=hf63aee3_1001
  - gst-plugins-base=1.14.4=hdf3bae2_1001
  - gstreamer=1.14.4=h66beb1c_1001
  - gunicorn=19.9.0=py37_1000
  - hdf4=4.2.13=h9a582f1_1002
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - icu=58.2=hf484d3e_1000
  - idna=2.8=py37_1000
  - imageio=2.5.0=py37_0
  - ipython_genutils=0.2.0=py_1
  - itsdangerous=1.1.0=py_0
  - jansson=2.11=h516909a_1001
  - jinja2=2.10.1=py_0
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h14c3975_1001
  - kealib=1.4.10=h1978553_1003
  - kiwisolver=1.1.0=py37hc9558a2_0
  - krb5=1.16.3=h05b26f9_1001
  - libblas=3.8.0=7_openblas
  - libcblas=3.8.0=7_openblas
  - libcurl=7.64.1=hda55be3_0
  - libdap4=3.19.1=hd48c02d_1000
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgdal=2.4.1=hdb8f723_0
  - libgfortran=3.0.0=1
  - libiconv=1.15=h516909a_1005
  - libkml=1.3.0=h328b03d_1009
  - liblapack=3.8.0=7_openblas
  - libnetcdf=4.6.2=hbdf4f91_1001
  - libpng=1.6.37=hed695b0_0
  - libpq=11.3=h4e4e079_0
  - libspatialite=4.3.0a=hb5ec416_1026
  - libssh2=1.8.2=h22169c7_2
  - libtiff=4.0.10=h648cc4a_1001
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_0
  - libxslt=1.1.32=h4785a14_1002
  - lxml=4.3.3=py37h7ec2d77_0
  - markupsafe=1.1.1=py37h14c3975_0
  - matplotlib=3.1.0=py37_1
  - matplotlib-base=3.1.0=py37hfd891ef_1
  - metpy=0.10.0=py37_1001
  - ncurses=6.1=hf484d3e_1002
  - netcdf4=1.5.1.2=py37had58050_0
  - networkx=2.3=py_0
  - numpy=1.16.4=py37h95a1406_0
  - olefile=0.46=py_0
  - openblas=0.3.5=ha44fe06_0
  - openjpeg=2.3.1=h58a6597_0
  - openssl=1.1.1b=h14c3975_1
  - owslib=0.17.1=py_0
  - packaging=19.0=py_0
  - pandas=0.24.2=py37hb3f55d8_0
  - pcre=8.41=hf484d3e_1003
  - pillow=6.0.0=py37he7afcd5_0
  - pint=0.9=py37_2
  - pip=19.1=py37_0
  - pixman=0.34.0=h14c3975_1003
  - ply=3.11=py_1
  - pooch=0.2.1=py37_1000
  - poppler=0.67.0=h2ad7f00_6
  - poppler-data=0.4.9=1
  - postgresql=11.3=hbeee2d4_0
  - proj4=5.2.0=he1b5a44_1003
  - pthread-stubs=0.4=h14c3975_1001
  - pycparser=2.19=py37_1
  - pyepsg=0.4.0=py_0
  - pykdtree=1.3.1=py37h3010b51_1002
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.0=py_0
  - pyproj=1.9.6=py37h516909a_1002
  - pyqt=5.9.2=py37hcca6a23_0
  - pyresample=1.12.3=py37hf2d7682_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.0=py37_0
  - python=3.7.3=h5b0a415_0
  - python-dateutil=2.8.0=py_0
  - pytz=2019.1=py_0
  - pywavelets=1.0.3=py37hd352d35_1
  - pyyaml=5.1=py37h14c3975_0
  - qt=5.9.7=h52cfd70_2
  - readline=7.0=hf8c457e_1001
  - requests=2.22.0=py37_0
  - scikit-image=0.15.0=py37he1b5a44_0
  - scipy=1.3.0=py37h921218d_0
  - seawater=3.3.4=py_1
  - setuptools=41.0.1=py37_0
  - shapely=1.6.4=py37h2afed24_1004
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.12.0=py37_1000
  - soupsieve=1.9.1=py37_0
  - sqlite=3.28.0=h8b20d00_0
  - thredds_crawler=1.5.4=py_1
  - tk=8.6.9=h84994c4_1001
  - toolz=0.9.0=py_1
  - tornado=6.0.2=py37h516909a_0
  - traitlets=4.3.2=py37_1000
  - tzcode=2019a=h516909a_1002
  - urllib3=1.24.3=py37_0
  - uwsgi=2.0.18=py37h4472670_1
  - werkzeug=0.14.1=py_0
  - wheel=0.33.4=py37_0
  - xarray=0.12.1=py_0
  - xerces-c=3.2.2=hac72e42_1001
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.9=h516909a_1004
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.7=h14c3975_1000
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zlib=1.2.11=h14c3975_1004
  - anaconda=custom=py37_0
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
prefix: /opt/tools/miniconda3/envs/navigator

