name: navigator
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.9.0=pyh29332c3_0
  - aom=3.9.1=hac33072_0
  - arcosparse=0.4.2=pyhd8ed1ab_0
  - aws-c-auth=0.9.0=h0fbd49f_19
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.5=h149bd38_3
  - aws-c-http=0.10.4=h37a7233_0
  - aws-c-io=0.21.2=h1d8da38_0
  - aws-c-mqtt=0.13.3=h19deb91_3
  - aws-c-s3=0.8.6=h800fcd2_2
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.33.1=hb4fd278_2
  - aws-sdk-cpp=1.11.606=h31ade35_1
  - azure-core-cpp=1.16.0=h3a458e0_0
  - azure-identity-cpp=1.12.0=ha729027_0
  - azure-storage-blobs-cpp=12.14.0=hb1c9500_1
  - azure-storage-common-cpp=12.10.0=hebae86a_2
  - azure-storage-files-datalake-cpp=12.12.0=h8b27e44_3
  - babel=2.17.0=pyhd8ed1ab_0
  - blosc=1.21.6=he440d0b_1
  - bokeh=3.7.3=pyhd8ed1ab_0
  - boto3=1.39.11=pyhd8ed1ab_0
  - botocore=1.39.12=pyge310_1234567_0
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.1.0=py313h46c70d0_3
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.19.1=h4cfbee9_0
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.1.0=pyhd8ed1ab_0
  - cairo=1.18.4=h3394656_0
  - cartopy=0.24.0=py313ha87cce1_0
  - certifi=2025.7.14=pyhd8ed1ab_0
  - cffi=1.17.1=py313hfab6e84_0
  - cftime=1.6.4=py313ha014f3b_1
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - cmocean=4.0.3=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorspacious=1.1.2=pyhecae5ae_1
  - configobj=5.0.9=pyhd8ed1ab_1
  - contourpy=1.3.2=py313h33d0bda_0
  - copernicusmarine=2.2.1=pyhd8ed1ab_0
  - crc32c=2.7.1=py313h536fd9c_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - cytoolz=1.0.1=py313h536fd9c_0
  - dask=2025.7.0=pyhe01879c_0
  - dask-core=2025.7.0=pyhe01879c_1
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - distributed=2025.7.0=pyhe01879c_0
  - dnspython=2.7.0=pyhff2d567_1
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - double-conversion=3.3.1=h5888daf_0
  - email-validator=2.2.0=pyhd8ed1ab_1
  - email_validator=2.2.0=hd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - fastapi=0.116.1=h26c32bb_1
  - fastapi-cli=0.0.8=pyhd8ed1ab_0
  - fastapi-core=0.116.1=pyhe01879c_1
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.0=py313h3dea7bd_0
  - freetype=2.13.3=ha770c72_1
  - freexl=2.0.0=h9dce30a_2
  - fsspec=2025.7.0=pyhd8ed1ab_0
  - gdal=3.11.3=py313h60f829d_0
  - geographiclib=2.0=pyhd8ed1ab_1
  - geojson=3.2.0=pyhd8ed1ab_0
  - geopy=2.4.1=pyhd8ed1ab_2
  - geos=3.13.1=h97f6797_0
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - graphite2=1.3.14=h5888daf_0
  - greenlet=3.2.3=py313h46c70d0_0
  - gsw=3.6.19=py313ha014f3b_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5netcdf=1.6.3=pyhd8ed1ab_0
  - h5py=3.14.0=nompi_py313hfaf8fd4_100
  - harfbuzz=11.3.2=hbb57e21_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.6.4=py313h536fd9c_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hypercorn=0.17.3=pyhd8ed1ab_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - imagecodecs=2025.3.30=py313h8b391ee_2
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_1
  - json-c=0.18=h6688a6e_0
  - jxrlib=1.1=hd590300_3
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py313h33d0bda_1
  - krb5=1.21.3=h659f571_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.8.1=gpl_h98cc613_100
  - libarrow=20.0.0=h62dcc0a_18_cpu
  - libarrow-acero=20.0.0=h635bf11_18_cpu
  - libarrow-dataset=20.0.0=h635bf11_18_cpu
  - libarrow-substrait=20.0.0=h3f74fd7_18_cpu
  - libavif16=1.3.0=h766b0b6_0
  - libblas=3.9.0=32_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.9.0=32_he106b2a_openblas
  - libclang-cpp20.1=20.1.8=default_hddf928d_0
  - libclang13=20.1.8=default_ha444ac7_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgdal-core=3.11.3=ha8f0914_0
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h3618099_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_3
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h1e535eb_0
  - libhwy=1.2.0=hf40a0c7_0
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libjxl=0.11.1=h7b0646d_2
  - libkml=1.3.0=hf539b9f_1021
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnetcdf=4.9.2=nompi_h0134ee8_117
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=20.0.0=h790f06f_18_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h943b412_0
  - libpq=17.5=h27ae623_0
  - libprotobuf=6.31.1=h9ef548d_1
  - libre2-11=2025.07.22=h7b12aa8_0
  - librttopo=1.1.0=hd718a1a_18
  - libspatialite=5.1.0=he17ca71_14
  - libsqlite=3.50.3=hee844dc_1
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.0=hf01ce69_5
  - libutf8proc=2.10.0=h202a827_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb9d3cd8_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libxslt=1.1.43=h7a3aeb2_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.4=py313h8756d67_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - mariadb=1.1.12=py313h46c70d0_0
  - mariadb-connector-c=3.4.6=h10329db_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py313h8060acc_1
  - matplotlib=3.10.3=py313h78bf25f_0
  - matplotlib-base=3.10.3=py313h129903b_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - metpy=1.7.0=pyhd8ed1ab_0
  - minizip=4.0.10=h05a5f5f_0
  - msgpack-python=1.1.1=py313h33d0bda_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=h5888daf_0
  - mysql-common=9.3.0=h266115a_0
  - mysql-libs=9.3.0=he0572af_0
  - mysqlclient=2.2.7=py313h6034b36_2
  - narwhals=1.48.0=pyhe01879c_0
  - ncurses=6.5=h2d0b736_3
  - netcdf4=1.7.2=nompi_py313h6d1955d_102
  - networkx=3.5=pyhe01879c_0
  - nlohmann_json=3.12.0=h3f2d84a_0
  - numcodecs=0.16.1=py313ha87cce1_0
  - numpy=2.3.1=py313hf6604e3_1
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.1=h7b32b05_0
  - orc=2.1.3=h61e0c1e_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py313h08cd8bf_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.45=hc749103_0
  - pillow=11.3.0=py313h8db990d_0
  - pint=0.24.4=pyhe01879c_2
  - pip=25.1.1=pyh145f28c_0
  - pixman=0.46.4=h537e5f6_0
  - platformdirs=4.3.8=pyhe01879c_0
  - ply=3.11=pyhd8ed1ab_3
  - pooch=1.8.2=pyhd8ed1ab_1
  - priority=2.0.0=pyhd8ed1ab_1
  - proj=9.6.2=h0054346_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - psutil=7.0.0=py313h536fd9c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyarrow=20.0.0=py313h78bf25f_0
  - pyarrow-core=20.0.0=py313he5f92c8_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py313h4b2b08d_0
  - pydantic-settings=2.10.1=pyh3cfb1c2_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyinstrument=5.0.3=py313h536fd9c_0
  - pykdtree=1.4.2=py313ha014f3b_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyproj=3.7.1=py313hcd509b5_1
  - pyresample=1.34.2=py313h46c70d0_0
  - pyshp=2.3.1=pyhd8ed1ab_1
  - pyside6=6.9.1=py313h7dabd7a_0
  - pysocks=1.7.1=pyha55dd90_7
  - pystac=1.13.0=pyhd8ed1ab_0
  - python=3.13.5=hec9711d_102_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.1.1=pyhe01879c_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytest       
  - pytest-cov       
  - pytest-mock
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.8.0=py313ha014f3b_0
  - pyyaml=6.0.2=py313h8060acc_2
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.1=h0384650_1
  - rav1e=0.7.1=h8fae777_3
  - re2=2025.07.22=h5a314c3_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.4=pyhd8ed1ab_0
  - rich=14.0.0=pyh29332c3_0
  - rich-toolkit=0.14.8=pyhe01879c_0
  - s2n=1.5.22=h96f233e_0
  - s3transfer=0.13.1=pyhd8ed1ab_0
  - scikit-image=0.25.2=py313ha87cce1_1
  - scipy=1.16.0=py313h86fcf2b_0
  - semver=3.0.4=pyhd8ed1ab_0
  - sentry-sdk=2.33.2=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.1=py313h576e190_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sqlalchemy=2.0.41=py313h536fd9c_0
  - sqlite=3.50.3=heff268d_1
  - starlette=0.47.1=pyh82d4cca_0
  - svt-av1=3.0.2=h5888daf_0
  - taskgroup=0.2.2=pyhd8ed1ab_0
  - tblib=3.1.0=pyhd8ed1ab_0
  - tifffile=2025.6.11=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - tomli=2.2.1=pyhd8ed1ab_1
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5.1=py313h536fd9c_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.16.0=pyh167b9f4_0
  - typer-slim=0.16.0=pyhe01879c_0
  - typer-slim-standard=0.16.0=hf964461_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - uvicorn=0.35.0=pyh31011fe_0
  - uvicorn-standard=0.35.0=h31011fe_0
  - uvloop=0.21.0=py313h536fd9c_1
  - watchfiles=1.1.0=py313h920b4c0_0
  - wayland=1.24.0=h3e06ad9_0
  - websockets=15.0.1=py313h536fd9c_0
  - wrapt=1.17.2=py313h536fd9c_0
  - wsproto=1.2.0=pyhd8ed1ab_1
  - xarray=2025.7.1=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xerces-c=3.2.5=h988505b_2
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zarr=3.1.0=pyhe01879c_0
  - zfp=1.0.1=h5888daf_2
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.4=h7955e40_0
  - zstandard=0.23.0=py313h536fd9c_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - visvalingamwyatt==0.3.0

prefix: "/home/ubuntu/miniforge3/envs/navigator"
